In [2]:
import pandas as pd
import numpy as np

## ARRAY GENERATION


In [11]:
a = np.array([1,2,3,4,5,6])

In [13]:
type(a)

numpy.ndarray

In [22]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])

In [23]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [33]:
c = np.array([1,2,3], dtype = float) #float, bool, complex

In [34]:
c

array([1., 2., 3.])

In [37]:
np.arange(1,11,2)  # start, stop+1, step

array([1, 3, 5, 7, 9])

In [43]:
np.arange(1,121).reshape(2,3,4,5) #last 2 are rows and columns, numbers in starting define the Nth Dimensional matrix
# here there are 4 rows with 5 columns, and there are 2 groups and each group has 3 subgroups
# so basically in .reshape(a,b,c,d....x,y,z) -> there will be y rows with z columns, in groups of a, each group of a
# will have b subgroups, each subgroup b will have c subgorups and so on...

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.random.random((3,3))

array([[0.58874932, 0.35575282, 0.21804572],
       [0.46234395, 0.20516292, 0.04518669],
       [0.14198049, 0.54883143, 0.90171769]])

In [49]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [50]:
np.linspace(10,100,10) #generates equally spaced series of numbers for a start and end
# the step is calculated as, step = (stop - start)/(num-1) where num is the no. of numbers required

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [51]:
np.empty((2,3)) #similar to np.zeroes but considered faster

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.eye(3, 4) #generates identity matrix but for non-square 2d arrays

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## ARRAY ATTRIBUTES

In [71]:
a1 = np.arange(1,10, dtype = np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [60]:
a3.ndim #no of dimensions

3

In [63]:
a3.shape #(groups, rows, columns)

(2, 2, 2)

In [64]:
a3.size #total elements

8

In [67]:
a3.itemsize #total space taken in memory, int64 takes 8 bytes and int32 takes 4 bytes, and int64 is default size

8

In [74]:
a1.dtype

dtype('int32')

In [79]:
a1 = a1.astype(np.int64) # you need to store astype output in new array, then only dtype changes


In [80]:
a1.dtype

dtype('int64')

## ARRAY OPERATIONS

In [82]:
a2 = np.arange(12,24).reshape(3,4)
a1 = np.arange(12).reshape(3,4)

In [84]:
a1 ** 2 #here 2 is scalar - so this is scalar operator

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [88]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
a1*a2 #not follow actual matrix multiplication

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## ARRAY OPERATIONS

In [104]:
a1 = np.round(np.random.random((3,3)) * 100)

In [105]:
a1

array([[55., 67., 35.],
       [28.,  5., 23.],
       [44., 43., 28.]])

### AGGREGATION FUNCTIONS

In [106]:
print(f'Max of a1 array elements is', np.max(a1))
print(f'Min of a1 array elements is', np.min(a1))
print(f'Sum of a1 array elements is', np.sum(a1))
print(f'Product of a1 array elements is', np.prod(a1))


Max of a1 array elements is 67.0
Min of a1 array elements is 5.0
Sum of a1 array elements is 328.0
Product of a1 array elements is 22000906312000.0


In [107]:
# ----- Along Axis 0 (Column-wise) -----
# Axis 0 means operate DOWN each column

print(f'Max of each column: {np.max(a1, axis=0)}')
print(f'Min of each column: {np.min(a1, axis=0)}')
print(f'Sum of each column: {np.sum(a1, axis=0)}')
print(f'Product of each column: {np.prod(a1, axis=0)}')


# ----- Along Axis 1 (Row-wise) -----
# Axis 1 means operate ACROSS each row

print(f'Max of each row: {np.max(a1, axis=1)}')
print(f'Min of each row: {np.min(a1, axis=1)}')
print(f'Sum of each row: {np.sum(a1, axis=1)}')
print(f'Product of each row: {np.prod(a1, axis=1)}')

Max of each column: [55. 67. 35.]
Min of each column: [28.  5. 23.]
Sum of each column: [127. 115.  86.]
Product of each column: [67760. 14405. 22540.]
Max of each row: [67. 28. 44.]
Min of each row: [35.  5. 28.]
Sum of each row: [157.  56. 115.]
Product of each row: [128975.   3220.  52976.]


### STATISTICAL FUNCTIONS

In [108]:
# ----- Overall -----

print(f'Mean of a1 array elements is {np.mean(a1)}')
print(f'Median of a1 array elements is {np.median(a1)}')
print(f'Standard Deviation of a1 array elements is {np.std(a1)}')
print(f'Variance of a1 array elements is {np.var(a1)}')


Mean of a1 array elements is 36.44444444444444
Median of a1 array elements is 35.0
Standard Deviation of a1 array elements is 17.29554284979618
Variance of a1 array elements is 299.1358024691358


In [109]:
# ----- Along Axis 0 (Column-wise) -----
# Axis 0 means operate DOWN each column

print(f'Mean of each column: {np.mean(a1, axis=0)}')
print(f'Median of each column: {np.median(a1, axis=0)}')
print(f'Standard Deviation of each column: {np.std(a1, axis=0)}')
print(f'Variance of each column: {np.var(a1, axis=0)}')


# ----- Along Axis 1 (Row-wise) -----
# Axis 1 means operate ACROSS each row

print(f'Mean of each row: {np.mean(a1, axis=1)}')
print(f'Median of each row: {np.median(a1, axis=1)}')
print(f'Standard Deviation of each row: {np.std(a1, axis=1)}')
print(f'Variance of each row: {np.var(a1, axis=1)}')

Mean of each column: [42.33333333 38.33333333 28.66666667]
Median of each column: [44. 43. 28.]
Standard Deviation of each column: [11.0855261  25.52558629  4.92160769]
Variance of each column: [122.88888889 651.55555556  24.22222222]
Mean of each row: [52.33333333 18.66666667 38.33333333]
Median of each row: [55. 23. 43.]
Standard Deviation of each row: [13.19932658  9.87702159  7.31816613]
Variance of each row: [174.22222222  97.55555556  53.55555556]


In [111]:
# ----- Trigonometric Functions (Element-wise) -----
# Note: Input values are assumed to be in RADIANS

print(f'Sine of a1:\n{np.sin(a1)}')
print(f'Cosine of a1:\n{np.cos(a1)}')
print(f'Tangent of a1:\n{np.tan(a1)}')


Sine of a1:
[[-0.99975517 -0.85551998 -0.42818267]
 [ 0.27090579 -0.95892427 -0.8462204 ]
 [ 0.01770193 -0.83177474  0.27090579]]
Cosine of a1:
[[ 0.02212676 -0.5177698  -0.90369221]
 [-0.96260587  0.28366219 -0.53283302]
 [ 0.99984331  0.5551133  -0.96260587]]
Tangent of a1:
[[-4.51830879e+01  1.65231726e+00  4.73814720e-01]
 [-2.81429605e-01 -3.38051501e+00  1.58815308e+00]
 [ 1.77046993e-02 -1.49838734e+00 -2.81429605e-01]]


### DOT PRODUCT

In [114]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(24,36).reshape(4,3)

In [116]:
print(f'Dot Product of a2 and a3:\n{np.dot(a2,a3)}')

Dot Product of a2 and a3:
[[ 186  192  198]
 [ 642  664  686]
 [1098 1136 1174]]


## Indexing and Slicing

### INDEXING

In [117]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [118]:
# ==========================================================
# 1D ARRAY INDEXING
# ==========================================================

print(a1)

print(a1[0])      # First element
print(a1[4])      # Fifth element
print(a1[-1])     # Last element
print(a1[-2])     # Second last element

[0 1 2 3 4 5 6 7 8 9]
0
4
9
8


In [119]:
# ==========================================================
# 2D ARRAY INDEXING
# ==========================================================

print(a2)

print(a2[0])          # First row
print(a2[1])          # Second row
print(a2[-1])         # Last row

print(a2[0,0])        # First row, first column
print(a2[1,2])        # Second row, third column
print(a2[2,3])        # Last row, last column
print(a2[-1,-1])      # Last element

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
6
11
11


In [120]:
# ==========================================================
# 3D ARRAY INDEXING
# ==========================================================

print(a3)

print(a3[0])          # First 2x2 matrix
print(a3[1])          # Second 2x2 matrix

print(a3[0,0])        # First row of first matrix
print(a3[1,1])        # Second row of second matrix

print(a3[0,1,0])      # First matrix, second row, first column
print(a3[1,0,1])      # Second matrix, first row, second column
print(a3[1,1,1])      # Last element
print(a3[-1,-1,-1])   # Last element using negative indexing

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[0 1]
[6 7]
2
5
7
7


### SLICING

In [148]:
# used to extract a particular or a group of elements
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
a1[0:6:2]

array([0, 2, 4])

In [132]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [137]:
a2[::2,::3] #to get all corner elements

array([[ 0,  3],
       [ 8, 11]])

In [147]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [156]:
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

## NumPy Slicing Practice Questions

### 2d array (cuz 1d is way too easyy)

Assume the following array:

```python
import numpy as np

a2 = np.arange(12).reshape(3,4)

# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])
```

---

### 1. Extract the first row.

**Expected Output**

```python
array([0, 1, 2, 3])
```

---

### 2. Extract the last column.

**Expected Output**

```python
array([ 3,  7, 11])
```

---

### 3. Extract the first two rows.

**Expected Output**

```python
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
```

---

### 4. Extract the middle 2×2 block.

**Expected Output**

```python
array([[ 5,  6],
       [ 9, 10]])
```

---

### 5. Extract every alternate column.

**Expected Output**

```python
array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])
```

---

### 6. Extract every alternate row.

**Expected Output**

```python
array([[0, 1, 2, 3],
       [8, 9, 10, 11]])
```

---

### 7. Extract the four corner elements.

**Expected Output**

```python
array([[ 0,  3],
       [ 8, 11]])
```

---

### 8. Reverse the columns.

**Expected Output**

```python
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```

---

### 9. Reverse both rows and columns.

**Expected Output**

```python
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```

---

### 10. Extract only the even-indexed rows and odd-indexed columns.

**Expected Output**

```python
array([[ 1,  3],
       [ 9, 11]])
```

In [157]:
a3 = np.arange(27).reshape(3,3,3)

In [158]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

## NumPy 3D Array Slicing Practice Questions

Assume the following array:

```python
import numpy as np

a3 = np.arange(27).reshape(3,3,3)

# array([[[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8]],
#
#        [[ 9, 10, 11],
#         [12, 13, 14],
#         [15, 16, 17]],
#
#        [[18, 19, 20],
#         [21, 22, 23],
#         [24, 25, 26]]])
```

---

### 1. Extract the first 3×3 matrix.

**Expected Output**

```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

---

### 2. Extract the last 3×3 matrix.

**Expected Output**

```python
array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])
```

---

### 3. Extract the first row from every matrix.

**Expected Output**

```python
array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])
```

---

### 4. Extract the last column from every matrix.

**Expected Output**

```python
array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])
```

---

### 5. Extract the center element from every matrix.

**Expected Output**

```python
array([ 4, 13, 22])
```

---

### 6. Extract the first two matrices.

**Expected Output**

```python
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])
```

---

### 7. Extract the top-left 2×2 block from every matrix.

**Expected Output**

```python
array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]],

       [[18, 19],
        [21, 22]]])
```

---

### 8. Reverse the order of the matrices.

**Expected Output**

```python
array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])
```

---

### 9. Reverse the rows and columns within every matrix.

**Expected Output**

```python
array([[[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]]])
```

---

### 10. Extract the four corner elements from every matrix.

**Expected Output**

```python
array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])
```

## ITERATION

In [181]:

a1 = np.arange(5)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)


# ==========================================================
# ITERATION
# ==========================================================

# 1D Array -> Each iteration returns an element
for element in a1:
    print(element)


# 2D Array -> Each iteration returns a row (1D array)
for row in a2:
    print(row)


# 3D Array -> Each iteration returns a 2D matrix
for matrix in a3:
    print(matrix)


# ==========================================================
# np.nditer()
# ==========================================================

# Iterates over every element irrespective of array dimensions

for element in np.nditer(a1):
    print(element)

for element in np.nditer(a2):
    print(element)

for element in np.nditer(a3):
    print(element)

0
1
2
3
4
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## RESHAPING"

In [184]:
# ==========================================================
# RESHAPING ARRAYS
# ==========================================================
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

# reshape() -> Changes the shape of an array
# Total number of elements must remain the same

print(a1.reshape(2,5))
print(a2.reshape(2,6))
print(a3.reshape(9,3))


# ==========================================================
# TRANSPOSE
# ==========================================================

# transpose() -> Swaps the axes of an array
# For a 2D array: rows become columns and columns become rows

print(a2.T)
print(a2.transpose())

# For higher-dimensional arrays, transpose swaps the axes
print(a3.transpose())


# ==========================================================
# RAVEL
# ==========================================================

# ravel() -> Flattens an n-dimensional array into a 1D array

print(a2.ravel())
print(a3.ravel())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


## STACKING

In [185]:

# Sample arrays

a4 = np.array([[1, 2, 3],
               [4, 5, 6]])

a5 = np.array([[7, 8, 9],
               [10, 11, 12]])


# ==========================================================
# HORIZONTAL STACKING
# ==========================================================

# hstack() -> Joins arrays column-wise
# Number of rows must be the same

print(np.hstack((a4, a5)))

# Output:
# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]


# ==========================================================
# VERTICAL STACKING
# ==========================================================

# vstack() -> Joins arrays row-wise
# Number of columns must be the same

print(np.vstack((a4, a5)))

# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## SPLITTING

In [186]:
# ==========================================================
# SPLITTING ARRAYS
# ==========================================================

# Sample array

a4 = np.array([[ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12],
               [13, 14, 15, 16]])


# ==========================================================
# HORIZONTAL SPLITTING
# ==========================================================

# hsplit() -> Splits an array column-wise
# Condition: Number of columns must be equally divisible

print(np.hsplit(a4, 2))

# Output:
# [array([[ 1,  2],
#         [ 5,  6],
#         [ 9, 10],
#         [13, 14]]),
#
#  array([[ 3,  4],
#         [ 7,  8],
#         [11, 12],
#         [15, 16]])]


# ==========================================================
# VERTICAL SPLITTING
# ==========================================================

# vsplit() -> Splits an array row-wise
# Condition: Number of rows must be equally divisible

print(np.vsplit(a4, 2))

# Output:
# [array([[1, 2, 3, 4],
#         [5, 6, 7, 8]]),
#
#  array([[ 9, 10, 11, 12],
#         [13, 14, 15, 16]])]

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
